package com.utonw.dealer.api.model;

public class ContactPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_person.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_person.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_person.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_person.p_index
     *
     * @mbggenerated
     */
    private Integer pIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_person.id
     *
     * @return the value of contact_person.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_person.id
     *
     * @param id the value for contact_person.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_person.position
     *
     * @return the value of contact_person.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_person.position
     *
     * @param position the value for contact_person.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_person.phone
     *
     * @return the value of contact_person.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_person.phone
     *
     * @param phone the value for contact_person.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_person.p_index
     *
     * @return the value of contact_person.p_index
     *
     * @mbggenerated
     */
    public Integer getpIndex() {
        return pIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_person.p_index
     *
     * @param pIndex the value for contact_person.p_index
     *
     * @mbggenerated
     */
    public void setpIndex(Integer pIndex) {
        this.pIndex = pIndex;
    }
}