package com.utonw.dealer.api.model;

import java.util.Date;

public class MerchantPicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_picture.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_picture.acount_id
     *
     * @mbggenerated
     */
    private Long acountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_picture.file_title
     *
     * @mbggenerated
     */
    private Integer fileTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_picture.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_picture.contract_url
     *
     * @mbggenerated
     */
    private String contractUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_picture.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_picture.id
     *
     * @return the value of merchant_picture.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_picture.id
     *
     * @param id the value for merchant_picture.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Long getAcountId() {
        return acountId;
    }

    public void setAcountId(Long acountId) {
        this.acountId = acountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_picture.file_title
     *
     * @return the value of merchant_picture.file_title
     *
     * @mbggenerated
     */
    public Integer getFileTitle() {
        return fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_picture.file_title
     *
     * @param fileTitle the value for merchant_picture.file_title
     *
     * @mbggenerated
     */
    public void setFileTitle(Integer fileTitle) {
        this.fileTitle = fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_picture.created_date
     *
     * @return the value of merchant_picture.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_picture.created_date
     *
     * @param createdDate the value for merchant_picture.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_picture.contract_url
     *
     * @return the value of merchant_picture.contract_url
     *
     * @mbggenerated
     */
    public String getContractUrl() {
        return contractUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_picture.contract_url
     *
     * @param contractUrl the value for merchant_picture.contract_url
     *
     * @mbggenerated
     */
    public void setContractUrl(String contractUrl) {
        this.contractUrl = contractUrl == null ? null : contractUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_picture.state
     *
     * @return the value of merchant_picture.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_picture.state
     *
     * @param state the value for merchant_picture.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}