package com.utonw.dealer.api.model;

public class MerchantContactPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_contact_person.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_contact_person.acount_id
     *
     * @mbggenerated
     */
    private Long acountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_contact_person.person_name
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_contact_person.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_contact_person.is_index
     *
     * @mbggenerated
     */
    private Integer isIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_contact_person.id
     *
     * @return the value of merchant_contact_person.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_contact_person.id
     *
     * @param id the value for merchant_contact_person.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Long getAcountId() {
        return acountId;
    }

    public void setAcountId(Long acountId) {
        this.acountId = acountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_contact_person.person_name
     *
     * @return the value of merchant_contact_person.person_name
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_contact_person.person_name
     *
     * @param personName the value for merchant_contact_person.person_name
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_contact_person.phone
     *
     * @return the value of merchant_contact_person.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_contact_person.phone
     *
     * @param phone the value for merchant_contact_person.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_contact_person.is_index
     *
     * @return the value of merchant_contact_person.is_index
     *
     * @mbggenerated
     */
    public Integer getIsIndex() {
        return isIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_contact_person.is_index
     *
     * @param isIndex the value for merchant_contact_person.is_index
     *
     * @mbggenerated
     */
    public void setIsIndex(Integer isIndex) {
        this.isIndex = isIndex;
    }
}