package com.utonw.dealer.api.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.acount_id
     *
     * @mbggenerated
     */
    private Long acountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.merchantName
     *
     * @mbggenerated
     */
    private String merchantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.license_number
     *
     * @mbggenerated
     */
    private String licenseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.organization_code
     *
     * @mbggenerated
     */
    private String organizationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.limit
     *
     * @mbggenerated
     */
    private BigDecimal limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.monthlyInterest
     *
     * @mbggenerated
     */
    private BigDecimal monthlyinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.loanLimit
     *
     * @mbggenerated
     */
    private BigDecimal loanlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.financing_number
     *
     * @mbggenerated
     */
    private Integer financingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.carport
     *
     * @mbggenerated
     */
    private Integer carport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.repertory
     *
     * @mbggenerated
     */
    private Integer repertory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.scale
     *
     * @mbggenerated
     */
    private String scale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.apply_data
     *
     * @mbggenerated
     */
    private Date applyData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_apply.apply_state
     *
     * @mbggenerated
     */
    private Integer applyState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.id
     *
     * @return the value of merchant_apply.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.id
     *
     * @param id the value for merchant_apply.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Long getAcountId() {
        return acountId;
    }

    public void setAcountId(Long acountId) {
        this.acountId = acountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.merchantName
     *
     * @return the value of merchant_apply.merchantName
     *
     * @mbggenerated
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.merchantName
     *
     * @param merchantname the value for merchant_apply.merchantName
     *
     * @mbggenerated
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname == null ? null : merchantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.license_number
     *
     * @return the value of merchant_apply.license_number
     *
     * @mbggenerated
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.license_number
     *
     * @param licenseNumber the value for merchant_apply.license_number
     *
     * @mbggenerated
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber == null ? null : licenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.organization_code
     *
     * @return the value of merchant_apply.organization_code
     *
     * @mbggenerated
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.organization_code
     *
     * @param organizationCode the value for merchant_apply.organization_code
     *
     * @mbggenerated
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.limit
     *
     * @return the value of merchant_apply.limit
     *
     * @mbggenerated
     */
    public BigDecimal getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.limit
     *
     * @param limit the value for merchant_apply.limit
     *
     * @mbggenerated
     */
    public void setLimit(BigDecimal limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.monthlyInterest
     *
     * @return the value of merchant_apply.monthlyInterest
     *
     * @mbggenerated
     */
    public BigDecimal getMonthlyinterest() {
        return monthlyinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.monthlyInterest
     *
     * @param monthlyinterest the value for merchant_apply.monthlyInterest
     *
     * @mbggenerated
     */
    public void setMonthlyinterest(BigDecimal monthlyinterest) {
        this.monthlyinterest = monthlyinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.loanLimit
     *
     * @return the value of merchant_apply.loanLimit
     *
     * @mbggenerated
     */
    public BigDecimal getLoanlimit() {
        return loanlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.loanLimit
     *
     * @param loanlimit the value for merchant_apply.loanLimit
     *
     * @mbggenerated
     */
    public void setLoanlimit(BigDecimal loanlimit) {
        this.loanlimit = loanlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.financing_number
     *
     * @return the value of merchant_apply.financing_number
     *
     * @mbggenerated
     */
    public Integer getFinancingNumber() {
        return financingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.financing_number
     *
     * @param financingNumber the value for merchant_apply.financing_number
     *
     * @mbggenerated
     */
    public void setFinancingNumber(Integer financingNumber) {
        this.financingNumber = financingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.carport
     *
     * @return the value of merchant_apply.carport
     *
     * @mbggenerated
     */
    public Integer getCarport() {
        return carport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.carport
     *
     * @param carport the value for merchant_apply.carport
     *
     * @mbggenerated
     */
    public void setCarport(Integer carport) {
        this.carport = carport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.repertory
     *
     * @return the value of merchant_apply.repertory
     *
     * @mbggenerated
     */
    public Integer getRepertory() {
        return repertory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.repertory
     *
     * @param repertory the value for merchant_apply.repertory
     *
     * @mbggenerated
     */
    public void setRepertory(Integer repertory) {
        this.repertory = repertory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.scale
     *
     * @return the value of merchant_apply.scale
     *
     * @mbggenerated
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.scale
     *
     * @param scale the value for merchant_apply.scale
     *
     * @mbggenerated
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.apply_data
     *
     * @return the value of merchant_apply.apply_data
     *
     * @mbggenerated
     */
    public Date getApplyData() {
        return applyData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.apply_data
     *
     * @param applyData the value for merchant_apply.apply_data
     *
     * @mbggenerated
     */
    public void setApplyData(Date applyData) {
        this.applyData = applyData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.update_time
     *
     * @return the value of merchant_apply.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.update_time
     *
     * @param updateTime the value for merchant_apply.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_apply.apply_state
     *
     * @return the value of merchant_apply.apply_state
     *
     * @mbggenerated
     */
    public Integer getApplyState() {
        return applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_apply.apply_state
     *
     * @param applyState the value for merchant_apply.apply_state
     *
     * @mbggenerated
     */
    public void setApplyState(Integer applyState) {
        this.applyState = applyState;
    }
}