package com.utonw.dealer.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CsdApprovalInfo implements Serializable{
    private static final long serialVersionUID = 8067560416037784035L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.orderId
     *
     * @mbggenerated
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.approvalStatus
     *
     * @mbggenerated
     */
    private String approvalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.approvalLevel
     *
     * @mbggenerated
     */
    private String approvallevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.approvalAmount
     *
     * @mbggenerated
     */
    private BigDecimal approvalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.approvalId
     *
     * @mbggenerated
     */
    private String approvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.approvalTime
     *
     * @mbggenerated
     */
    private Date approvaltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.lendedTime
     *
     * @mbggenerated
     */
    private Date lendedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.lendedPic
     *
     * @mbggenerated
     */
    private String lendedpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csd_approval_info.approvalConclusion
     *
     * @mbggenerated
     */
    private String approvalconclusion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.id
     *
     * @return the value of csd_approval_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.id
     *
     * @param id the value for csd_approval_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.orderId
     *
     * @return the value of csd_approval_info.orderId
     *
     * @mbggenerated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.orderId
     *
     * @param orderid the value for csd_approval_info.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.approvalStatus
     *
     * @return the value of csd_approval_info.approvalStatus
     *
     * @mbggenerated
     */
    public String getApprovalstatus() {
        return approvalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.approvalStatus
     *
     * @param approvalstatus the value for csd_approval_info.approvalStatus
     *
     * @mbggenerated
     */
    public void setApprovalstatus(String approvalstatus) {
        this.approvalstatus = approvalstatus == null ? null : approvalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.approvalLevel
     *
     * @return the value of csd_approval_info.approvalLevel
     *
     * @mbggenerated
     */
    public String getApprovallevel() {
        return approvallevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.approvalLevel
     *
     * @param approvallevel the value for csd_approval_info.approvalLevel
     *
     * @mbggenerated
     */
    public void setApprovallevel(String approvallevel) {
        this.approvallevel = approvallevel == null ? null : approvallevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.approvalAmount
     *
     * @return the value of csd_approval_info.approvalAmount
     *
     * @mbggenerated
     */
    public BigDecimal getApprovalamount() {
        return approvalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.approvalAmount
     *
     * @param approvalamount the value for csd_approval_info.approvalAmount
     *
     * @mbggenerated
     */
    public void setApprovalamount(BigDecimal approvalamount) {
        this.approvalamount = approvalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.approvalId
     *
     * @return the value of csd_approval_info.approvalId
     *
     * @mbggenerated
     */
    public String getApprovalid() {
        return approvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.approvalId
     *
     * @param approvalid the value for csd_approval_info.approvalId
     *
     * @mbggenerated
     */
    public void setApprovalid(String approvalid) {
        this.approvalid = approvalid == null ? null : approvalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.approvalTime
     *
     * @return the value of csd_approval_info.approvalTime
     *
     * @mbggenerated
     */
    public Date getApprovaltime() {
        return approvaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.approvalTime
     *
     * @param approvaltime the value for csd_approval_info.approvalTime
     *
     * @mbggenerated
     */
    public void setApprovaltime(Date approvaltime) {
        this.approvaltime = approvaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.lendedTime
     *
     * @return the value of csd_approval_info.lendedTime
     *
     * @mbggenerated
     */
    public Date getLendedtime() {
        return lendedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.lendedTime
     *
     * @param lendedtime the value for csd_approval_info.lendedTime
     *
     * @mbggenerated
     */
    public void setLendedtime(Date lendedtime) {
        this.lendedtime = lendedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.lendedPic
     *
     * @return the value of csd_approval_info.lendedPic
     *
     * @mbggenerated
     */
    public String getLendedpic() {
        return lendedpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.lendedPic
     *
     * @param lendedpic the value for csd_approval_info.lendedPic
     *
     * @mbggenerated
     */
    public void setLendedpic(String lendedpic) {
        this.lendedpic = lendedpic == null ? null : lendedpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csd_approval_info.approvalConclusion
     *
     * @return the value of csd_approval_info.approvalConclusion
     *
     * @mbggenerated
     */
    public String getApprovalconclusion() {
        return approvalconclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csd_approval_info.approvalConclusion
     *
     * @param approvalconclusion the value for csd_approval_info.approvalConclusion
     *
     * @mbggenerated
     */
    public void setApprovalconclusion(String approvalconclusion) {
        this.approvalconclusion = approvalconclusion == null ? null : approvalconclusion.trim();
    }
}