package com.utonw.dealer.api.entity;

import java.io.Serializable;
import java.util.Date;

public class TDistributionRfid implements Serializable {
    private static final long serialVersionUID = 4994141859448266882L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.dealer_id
     *
     * @mbggenerated
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.allocation_time
     *
     * @mbggenerated
     */
    private Date allocationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.creat_id
     *
     * @mbggenerated
     */
    private String creatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_distribution_rfid.update_id
     *
     * @mbggenerated
     */
    private String updateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.id
     *
     * @return the value of t_distribution_rfid.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.id
     *
     * @param id the value for t_distribution_rfid.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.user_id
     *
     * @return the value of t_distribution_rfid.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.user_id
     *
     * @param userId the value for t_distribution_rfid.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.dealer_id
     *
     * @return the value of t_distribution_rfid.dealer_id
     *
     * @mbggenerated
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.dealer_id
     *
     * @param dealerId the value for t_distribution_rfid.dealer_id
     *
     * @mbggenerated
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.allocation_time
     *
     * @return the value of t_distribution_rfid.allocation_time
     *
     * @mbggenerated
     */
    public Date getAllocationTime() {
        return allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.allocation_time
     *
     * @param allocationTime the value for t_distribution_rfid.allocation_time
     *
     * @mbggenerated
     */
    public void setAllocationTime(Date allocationTime) {
        this.allocationTime = allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.status
     *
     * @return the value of t_distribution_rfid.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.status
     *
     * @param status the value for t_distribution_rfid.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.create_time
     *
     * @return the value of t_distribution_rfid.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.create_time
     *
     * @param createTime the value for t_distribution_rfid.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.update_time
     *
     * @return the value of t_distribution_rfid.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.update_time
     *
     * @param updateTime the value for t_distribution_rfid.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.creat_id
     *
     * @return the value of t_distribution_rfid.creat_id
     *
     * @mbggenerated
     */
    public String getCreatId() {
        return creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.creat_id
     *
     * @param creatId the value for t_distribution_rfid.creat_id
     *
     * @mbggenerated
     */
    public void setCreatId(String creatId) {
        this.creatId = creatId == null ? null : creatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_distribution_rfid.update_id
     *
     * @return the value of t_distribution_rfid.update_id
     *
     * @mbggenerated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_distribution_rfid.update_id
     *
     * @param updateId the value for t_distribution_rfid.update_id
     *
     * @mbggenerated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }
}