package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;

public class CompanyWithBLOBs extends Company implements Serializable {
    private static final long serialVersionUID = 1863243409024562052L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.description
     *
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.remark
     *
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.description
     *
     * @return the value of company.description
     */

	public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.description
     *
     * @param description the value for company.description
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.remark
     *
     * @return the value of company.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.remark
     *
     * @param remark the value for company.remark
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}