package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CustomerRegisterInfo implements Serializable {

    private static final long serialVersionUID = -3355873155303001295L;
    /**
     * 是否是重点客户
     */
    private Integer isImportant;
    
    /**
     * 是否拉黑
     */
    private Integer  isBlacklist;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.uuid
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.id
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.customer_name
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.id_card
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.mobile
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.age
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.sex
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.education
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.marital_status
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.register_status
     */
    private String registerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.house
     */
    private String house;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.rental
     */
    private BigDecimal rental;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.live_number
     */
    private Integer liveNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.koseki_address
     */
    private String kosekiAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.live_address
     */
    private String liveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.create_cm_id
     */
    private String createCmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.responsible_cm_id
     */
    private String responsibleCmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.dept_id
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.company_id
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.created_at
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.updated_at
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_register_info.remark
     */
    private String remark;

    /**
     * 分销ID
     */
    private String orderId;

    /**
     * 分销员微信openId
     */
    private String openId;

    /**
     * 分销员提成比例
     */
    private String openIdrate;
    private Integer marry_period;
    private Integer number_of_children;
    private String status_of_children;
    private String home_tel;
    private Integer residence_period;
    private Integer residence_period_current;
    private Integer cohabitant;
    private Integer building_type;
    private  BigDecimal room_charge;
    private String business;

	public Integer getIsImportant() {
		return isImportant;
	}

	public void setIsImportant(Integer isImportant) {
		this.isImportant = isImportant;
	}

	public Integer getIsBlacklist() {
		return isBlacklist;
	}

	public void setIsBlacklist(Integer isBlacklist) {
		this.isBlacklist = isBlacklist;
	}

	public String getOpenIdrate() {
        return openIdrate;
    }

    public void setOpenIdrate(String openIdrate) {
        this.openIdrate = openIdrate;
    }

    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    private String creditCardBankName;//信用卡银行名称

    private String creditCardNum;// 信用卡张数
    private String creditCardQuota;//信用卡额度

    public String getCreditCardNum() {
        return creditCardNum;
    }

    public void setCreditCardNum(String creditCardNum) {
        this.creditCardNum = creditCardNum;
    }

    public String getCreditCardQuota() {
        return creditCardQuota;
    }

    public void setCreditCardQuota(String creditCardQuota) {
        this.creditCardQuota = creditCardQuota;
    }

    public String getCreditCardBankName() {
        return creditCardBankName;
    }

    public void setCreditCardBankName(String creditCardBankName) {
        this.creditCardBankName = creditCardBankName;
    }

    private String creditCard;//银行信用卡号

    public String getCreditCard() {
        return creditCard;
    }

    public void setCreditCard(String creditCard) {
        this.creditCard = creditCard;
    }

    private User user;
    private Company company;
    private Dept dept;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Dept getDept() {
        return dept;
    }

    public void setDept(Dept dept) {
        this.dept = dept;
    }
    

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.uuid
     *
     * @return the value of customer_register_info.uuid
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.uuid
     *
     * @param uuid the value for customer_register_info.uuid
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.id
     *
     * @return the value of customer_register_info.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.id
     *
     * @param id the value for customer_register_info.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.customer_name
     *
     * @return the value of customer_register_info.customer_name
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.customer_name
     *
     * @param customerName the value for customer_register_info.customer_name
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.id_card
     *
     * @return the value of customer_register_info.id_card
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.id_card
     *
     * @param idCard the value for customer_register_info.id_card
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.mobile
     *
     * @return the value of customer_register_info.mobile
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.mobile
     *
     * @param mobile the value for customer_register_info.mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.age
     *
     * @return the value of customer_register_info.age
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.age
     *
     * @param age the value for customer_register_info.age
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.sex
     *
     * @return the value of customer_register_info.sex
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.sex
     *
     * @param sex the value for customer_register_info.sex
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.education
     *
     * @return the value of customer_register_info.education
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.education
     *
     * @param education the value for customer_register_info.education
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.marital_status
     *
     * @return the value of customer_register_info.marital_status
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.marital_status
     *
     * @param maritalStatus the value for customer_register_info.marital_status
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.register_status
     *
     * @return the value of customer_register_info.register_status
     */
    public String getRegisterStatus() {
        return registerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.register_status
     *
     * @param registerStatus the value for customer_register_info.register_status
     */
    public void setRegisterStatus(String registerStatus) {
        this.registerStatus = registerStatus == null ? null : registerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.house
     *
     * @return the value of customer_register_info.house
     */
    public String getHouse() {
        return house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.house
     *
     * @param house the value for customer_register_info.house
     */
    public void setHouse(String house) {
        this.house = house == null ? null : house.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.rental
     *
     * @return the value of customer_register_info.rental
     */
    public BigDecimal getRental() {
        return rental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.rental
     *
     * @param rental the value for customer_register_info.rental
     */
    public void setRental(BigDecimal rental) {
        this.rental = rental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.live_number
     *
     * @return the value of customer_register_info.live_number
     */
    public Integer getLiveNumber() {
        return liveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.live_number
     *
     * @param liveNumber the value for customer_register_info.live_number
     */
    public void setLiveNumber(Integer liveNumber) {
        this.liveNumber = liveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.koseki_address
     *
     * @return the value of customer_register_info.koseki_address
     */
    public String getKosekiAddress() {
        return kosekiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.koseki_address
     *
     * @param kosekiAddress the value for customer_register_info.koseki_address
     */
    public void setKosekiAddress(String kosekiAddress) {
        this.kosekiAddress = kosekiAddress == null ? null : kosekiAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.live_address
     *
     * @return the value of customer_register_info.live_address
     */
    public String getLiveAddress() {
        return liveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.live_address
     *
     * @param liveAddress the value for customer_register_info.live_address
     */
    public void setLiveAddress(String liveAddress) {
        this.liveAddress = liveAddress == null ? null : liveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.create_cm_id
     *
     * @return the value of customer_register_info.create_cm_id
     */
    public String getCreateCmId() {
        return createCmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.create_cm_id
     *
     * @param createCmId the value for customer_register_info.create_cm_id
     */
    public void setCreateCmId(String createCmId) {
        this.createCmId = createCmId == null ? null : createCmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.responsible_cm_id
     *
     * @return the value of customer_register_info.responsible_cm_id
     */
    public String getResponsibleCmId() {
        return responsibleCmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.responsible_cm_id
     *
     * @param responsibleCmId the value for customer_register_info.responsible_cm_id
     */
    public void setResponsibleCmId(String responsibleCmId) {
        this.responsibleCmId = responsibleCmId == null ? null : responsibleCmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.dept_id
     *
     * @return the value of customer_register_info.dept_id
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.dept_id
     *
     * @param deptId the value for customer_register_info.dept_id
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.company_id
     *
     * @return the value of customer_register_info.company_id
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.company_id
     *
     * @param companyId the value for customer_register_info.company_id
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.created_at
     *
     * @return the value of customer_register_info.created_at
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.created_at
     *
     * @param createdAt the value for customer_register_info.created_at
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.updated_at
     *
     * @return the value of customer_register_info.updated_at
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.updated_at
     *
     * @param updatedAt the value for customer_register_info.updated_at
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_register_info.remark
     *
     * @return the value of customer_register_info.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_register_info.remark
     *
     * @param remark the value for customer_register_info.remark
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "CustomerRegisterInfo{" +
                "uuid='" + uuid + '\'' +
                ", id=" + id +
                ", customerName='" + customerName + '\'' +
                ", idCard='" + idCard + '\'' +
                ", mobile='" + mobile + '\'' +
                ", age=" + age +
                ", sex='" + sex + '\'' +
                ", education='" + education + '\'' +
                ", maritalStatus='" + maritalStatus + '\'' +
                ", registerStatus='" + registerStatus + '\'' +
                ", house='" + house + '\'' +
                ", rental=" + rental +
                ", liveNumber=" + liveNumber +
                ", kosekiAddress='" + kosekiAddress + '\'' +
                ", liveAddress='" + liveAddress + '\'' +
                ", createCmId='" + createCmId + '\'' +
                ", responsibleCmId='" + responsibleCmId + '\'' +
                ", deptId=" + deptId +
                ", companyId=" + companyId +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                ", remark='" + remark + '\'' +
//                ", isBlacklist='" + isBlacklist + '\'' +
//                ", isImportant='" + isImportant + '\'' +
                '}';
    }

    /**
     * 结婚时间
     */
    public Integer getMarry_period() {
        return marry_period;
    }

    public void setMarry_period(Integer marry_period) {
        this.marry_period = marry_period;
    }

    /**
     * 子女个数
     */
    public Integer getNumber_of_children() {
        return number_of_children;
    }

    public void setNumber_of_children(Integer number_of_children) {
        this.number_of_children = number_of_children;
    }

    /**
     * 子女状态(1:work,2:读书(高中以上)，3：读书(初中以上)，4，其他)
     */
    public String getStatus_of_children() {
        return status_of_children;
    }

    public void setStatus_of_children(String status_of_children) {
        this.status_of_children = status_of_children;
    }

    /**
     * 住宅电话
     */
    public String getHome_tel() {
        return home_tel;
    }

    public void setHome_tel(String home_tel) {
        this.home_tel = home_tel;
    }

    /**
     * 居住时间
     */
    public Integer getResidence_period() {
        return residence_period;
    }

    public void setResidence_period(Integer residence_period) {
        this.residence_period = residence_period;
    }

    /**
     * 现地居住时间
     */
    public Integer getResidence_period_current() {
        return residence_period_current;
    }

    public void setResidence_period_current(Integer residence_period_current) {
        this.residence_period_current = residence_period_current;
    }

    /**
     * 共同居住人[1:父母，2:子女，3:配偶，4:其他]
     */
    public Integer getCohabitant() {
        return cohabitant;
    }

    public void setCohabitant(Integer cohabitant) {
        this.cohabitant = cohabitant;
    }

    /**
     * 建筑类型(0:自建，1:自购，2:单位房，3:亲属住房，4:租房)
     */
    public Integer getBuilding_type() {
        return building_type;
    }

    public void setBuilding_type(Integer building_type) {
        this.building_type = building_type;
    }

    /**
     * 房租
     */
    public BigDecimal getRoom_charge() {
        return room_charge;
    }

    public void setRoom_charge(BigDecimal room_charge) {
        this.room_charge = room_charge;
    }

    public String getBusiness() {
        return business;
    }

    public void setBusiness(String business) {
        this.business = business;
    }
}