package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GuaranteeEvaluateInfo implements Serializable {
    private static final long serialVersionUID = 5920346354132254295L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.id
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.loan_id
     */
    private String loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.vehicle_brand
     */
    private String vehicleBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.vehicle_no
     */
    private String vehicleNo;


    private String vehicleModels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.mileaged
     */
    private String mileaged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.purchase_date
     */
    private Date purchaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.vehicle_identification
     */
    private String vehicleIdentification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.engine_no
     */
    private String engineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.transmission
     */
    private String transmission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.is_examined
     */
    private String isExamined;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.is_insure
     */
    private String isInsure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.is_province
     */
    private String isProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.indoor
     */
    private String indoor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.configuration
     */
    private String configuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.color
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.tire
     */
    private String tire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.displacement
     */
    private String displacement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.tool
     */
    private String tool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.dark_locks
     */
    private String darkLocks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.dark_locks_position
     */
    private String darkLocksPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.engine
     */
    private String engine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.price
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.buy_the_way
     */
    private String buyTheWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.evaluate_price
     */
    private BigDecimal evaluatePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.evaluate_conclusion
     */
    private String evaluateConclusion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.evaluateBy
     */
    private String evaluateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.created_at
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.updatedBy
     */
    private String updatedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.updated_at
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_evaluate_info.remark
     */
    private String remark;

    /**
     * 拖车状态
     */
    private String towStatus;


    /**
     * 出售金额
     */
    private BigDecimal saleMoney;

    private String vehicleRegisterCode;

    public BigDecimal getSaleMoney() {
        return saleMoney;
    }

    public void setSaleMoney(BigDecimal saleMoney) {
        this.saleMoney = saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.id
     *
     * @return the value of guarantee_evaluate_info.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.id
     *
     * @param id the value for guarantee_evaluate_info.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.loan_id
     *
     * @return the value of guarantee_evaluate_info.loan_id
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.loan_id
     *
     * @param loanId the value for guarantee_evaluate_info.loan_id
     */
    public void setLoanId(String loanId) {
        this.loanId = loanId == null ? null : loanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.vehicle_brand
     *
     * @return the value of guarantee_evaluate_info.vehicle_brand
     */
    public String getVehicleBrand() {
        return vehicleBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.vehicle_brand
     *
     * @param vehicleBrand the value for guarantee_evaluate_info.vehicle_brand
     */
    public void setVehicleBrand(String vehicleBrand) {
        this.vehicleBrand = vehicleBrand == null ? null : vehicleBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.vehicle_no
     *
     * @return the value of guarantee_evaluate_info.vehicle_no
     */
    public String getVehicleNo() {
        return vehicleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.vehicle_no
     *
     * @param vehicleNo the value for guarantee_evaluate_info.vehicle_no
     */
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo == null ? null : vehicleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.mileaged
     *
     * @return the value of guarantee_evaluate_info.mileaged
     */
    public String getMileaged() {
        return mileaged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.mileaged
     *
     * @param mileaged the value for guarantee_evaluate_info.mileaged
     */
    public void setMileaged(String mileaged) {
        this.mileaged = mileaged == null ? null : mileaged.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.purchase_date
     *
     * @return the value of guarantee_evaluate_info.purchase_date
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.purchase_date
     *
     * @param purchaseDate the value for guarantee_evaluate_info.purchase_date
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.vehicle_identification
     *
     * @return the value of guarantee_evaluate_info.vehicle_identification
     */
    public String getVehicleIdentification() {
        return vehicleIdentification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.vehicle_identification
     *
     * @param vehicleIdentification the value for guarantee_evaluate_info.vehicle_identification
     */
    public void setVehicleIdentification(String vehicleIdentification) {
        this.vehicleIdentification = vehicleIdentification == null ? null : vehicleIdentification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.engine_no
     *
     * @return the value of guarantee_evaluate_info.engine_no
     */
    public String getEngineNo() {
        return engineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.engine_no
     *
     * @param engineNo the value for guarantee_evaluate_info.engine_no
     */
    public void setEngineNo(String engineNo) {
        this.engineNo = engineNo == null ? null : engineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.transmission
     *
     * @return the value of guarantee_evaluate_info.transmission
     */
    public String getTransmission() {
        return transmission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.transmission
     *
     * @param transmission the value for guarantee_evaluate_info.transmission
     */
    public void setTransmission(String transmission) {
        this.transmission = transmission == null ? null : transmission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.is_examined
     *
     * @return the value of guarantee_evaluate_info.is_examined
     */
    public String getIsExamined() {
        return isExamined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.is_examined
     *
     * @param isExamined the value for guarantee_evaluate_info.is_examined
     */
    public void setIsExamined(String isExamined) {
        this.isExamined = isExamined == null ? null : isExamined.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.is_insure
     *
     * @return the value of guarantee_evaluate_info.is_insure
     */
    public String getIsInsure() {
        return isInsure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.is_insure
     *
     * @param isInsure the value for guarantee_evaluate_info.is_insure
     */
    public void setIsInsure(String isInsure) {
        this.isInsure = isInsure == null ? null : isInsure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.is_province
     *
     * @return the value of guarantee_evaluate_info.is_province
     */
    public String getIsProvince() {
        return isProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.is_province
     *
     * @param isProvince the value for guarantee_evaluate_info.is_province
     */
    public void setIsProvince(String isProvince) {
        this.isProvince = isProvince == null ? null : isProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.indoor
     *
     * @return the value of guarantee_evaluate_info.indoor
     */
    public String getIndoor() {
        return indoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.indoor
     *
     * @param indoor the value for guarantee_evaluate_info.indoor
     */
    public void setIndoor(String indoor) {
        this.indoor = indoor == null ? null : indoor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.configuration
     *
     * @return the value of guarantee_evaluate_info.configuration
     */
    public String getConfiguration() {
        return configuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.configuration
     *
     * @param configuration the value for guarantee_evaluate_info.configuration
     */
    public void setConfiguration(String configuration) {
        this.configuration = configuration == null ? null : configuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.color
     *
     * @return the value of guarantee_evaluate_info.color
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.color
     *
     * @param color the value for guarantee_evaluate_info.color
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.tire
     *
     * @return the value of guarantee_evaluate_info.tire
     */
    public String getTire() {
        return tire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.tire
     *
     * @param tire the value for guarantee_evaluate_info.tire
     */
    public void setTire(String tire) {
        this.tire = tire == null ? null : tire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.displacement
     *
     * @return the value of guarantee_evaluate_info.displacement
     */
    public String getDisplacement() {
        return displacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.displacement
     *
     * @param displacement the value for guarantee_evaluate_info.displacement
     */
    public void setDisplacement(String displacement) {
        this.displacement = displacement == null ? null : displacement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.tool
     *
     * @return the value of guarantee_evaluate_info.tool
     */
    public String getTool() {
        return tool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.tool
     *
     * @param tool the value for guarantee_evaluate_info.tool
     */
    public void setTool(String tool) {
        this.tool = tool == null ? null : tool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.dark_locks
     *
     * @return the value of guarantee_evaluate_info.dark_locks
     */
    public String getDarkLocks() {
        return darkLocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.dark_locks
     *
     * @param darkLocks the value for guarantee_evaluate_info.dark_locks
     */
    public void setDarkLocks(String darkLocks) {
        this.darkLocks = darkLocks == null ? null : darkLocks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.dark_locks_position
     *
     * @return the value of guarantee_evaluate_info.dark_locks_position
     */
    public String getDarkLocksPosition() {
        return darkLocksPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.dark_locks_position
     *
     * @param darkLocksPosition the value for guarantee_evaluate_info.dark_locks_position
     */
    public void setDarkLocksPosition(String darkLocksPosition) {
        this.darkLocksPosition = darkLocksPosition == null ? null : darkLocksPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.engine
     *
     * @return the value of guarantee_evaluate_info.engine
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.engine
     *
     * @param engine the value for guarantee_evaluate_info.engine
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.price
     *
     * @return the value of guarantee_evaluate_info.price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.price
     *
     * @param price the value for guarantee_evaluate_info.price
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.buy_the_way
     *
     * @return the value of guarantee_evaluate_info.buy_the_way
     */
    public String getBuyTheWay() {
        return buyTheWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.buy_the_way
     *
     * @param buyTheWay the value for guarantee_evaluate_info.buy_the_way
     */
    public void setBuyTheWay(String buyTheWay) {
        this.buyTheWay = buyTheWay == null ? null : buyTheWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.evaluate_price
     *
     * @return the value of guarantee_evaluate_info.evaluate_price
     */
    public BigDecimal getEvaluatePrice() {
        return evaluatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.evaluate_price
     *
     * @param evaluatePrice the value for guarantee_evaluate_info.evaluate_price
     */
    public void setEvaluatePrice(BigDecimal evaluatePrice) {
        this.evaluatePrice = evaluatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.evaluate_conclusion
     *
     * @return the value of guarantee_evaluate_info.evaluate_conclusion
     */
    public String getEvaluateConclusion() {
        return evaluateConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.evaluate_conclusion
     *
     * @param evaluateConclusion the value for guarantee_evaluate_info.evaluate_conclusion
     */
    public void setEvaluateConclusion(String evaluateConclusion) {
        this.evaluateConclusion = evaluateConclusion == null ? null : evaluateConclusion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.evaluateBy
     *
     * @return the value of guarantee_evaluate_info.evaluateBy
     */
    public String getEvaluateby() {
        return evaluateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.evaluateBy
     *
     * @param evaluateby the value for guarantee_evaluate_info.evaluateBy
     */
    public void setEvaluateby(String evaluateby) {
        this.evaluateby = evaluateby == null ? null : evaluateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.created_at
     *
     * @return the value of guarantee_evaluate_info.created_at
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.created_at
     *
     * @param createdAt the value for guarantee_evaluate_info.created_at
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.updatedBy
     *
     * @return the value of guarantee_evaluate_info.updatedBy
     */
    public String getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.updatedBy
     *
     * @param updatedby the value for guarantee_evaluate_info.updatedBy
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby == null ? null : updatedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.updated_at
     *
     * @return the value of guarantee_evaluate_info.updated_at
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.updated_at
     *
     * @param updatedAt the value for guarantee_evaluate_info.updated_at
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_evaluate_info.remark
     *
     * @return the value of guarantee_evaluate_info.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_evaluate_info.remark
     *
     * @param remark the value for guarantee_evaluate_info.remark
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }


    public String getTowStatus() {
        return towStatus;
    }

    public void setTowStatus(String towStatus) {
        this.towStatus = towStatus;
    }


    public String getVehicleModels() {
        return vehicleModels;
    }

    public void setVehicleModels(String vehicleModels) {
        this.vehicleModels = vehicleModels;
    }

    @Override
    public String toString() {
        return "GuaranteeEvaluateInfo{" +
                "id=" + id +
                ", loanId='" + loanId + '\'' +
                ", vehicleBrand='" + vehicleBrand + '\'' +
                ", vehicleNo='" + vehicleNo + '\'' +
                ", mileaged='" + mileaged + '\'' +
                ", purchaseDate=" + purchaseDate +
                ", vehicleIdentification='" + vehicleIdentification + '\'' +
                ", engineNo='" + engineNo + '\'' +
                ", transmission='" + transmission + '\'' +
                ", isExamined='" + isExamined + '\'' +
                ", isInsure='" + isInsure + '\'' +
                ", isProvince='" + isProvince + '\'' +
                ", indoor='" + indoor + '\'' +
                ", configuration='" + configuration + '\'' +
                ", color='" + color + '\'' +
                ", tire='" + tire + '\'' +
                ", displacement='" + displacement + '\'' +
                ", tool='" + tool + '\'' +
                ", darkLocks='" + darkLocks + '\'' +
                ", darkLocksPosition='" + darkLocksPosition + '\'' +
                ", engine='" + engine + '\'' +
                ", price=" + price +
                ", buyTheWay='" + buyTheWay + '\'' +
                ", evaluatePrice=" + evaluatePrice +
                ", evaluateConclusion='" + evaluateConclusion + '\'' +
                ", evaluateby='" + evaluateby + '\'' +
                ", createdAt=" + createdAt +
                ", updatedby='" + updatedby + '\'' +
                ", updatedAt=" + updatedAt +
                ", remark='" + remark + '\'' +
                ", towStatus='" + towStatus + '\'' +
                ", vehicleRegisterCode='" + vehicleRegisterCode + '\'' +
                '}';
    }

    /**
     * 机动车登记号码
     */
    public String getVehicleRegisterCode() {
        return vehicleRegisterCode;
    }

    public void setVehicleRegisterCode(String vehicleRegisterCode) {
        this.vehicleRegisterCode = vehicleRegisterCode;
    }
}