package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LoanInfo implements Serializable {
    private static final long serialVersionUID = 2015035983869654966L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.uuid
     *
     * @mbggenerated
     */
	private String state;
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.state
     * 是否加急
     * @mbggenerated
     */
	
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 流程实例id
     */


    private String  processinsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_money
     *
     * @mbggenerated
     */
    private BigDecimal loanMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.apply_money
     *
     * @mbggenerated
     */
    private BigDecimal applyMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_type
     *
     * @mbggenerated
     */
    private String loanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_status
     *
     * @mbggenerated
     */
    private String loanStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_way
     *
     * @mbggenerated
     */
    private String loanWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_purpose
     *
     * @mbggenerated
     */
    private String loanPurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.repay_source
     *
     * @mbggenerated
     */
    private String repaySource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_rate
     *
     * @mbggenerated
     */
    private BigDecimal loanRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_limit_time
     *
     * @mbggenerated
     */
    private Integer loanLimitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_limit_time_unit
     *
     * @mbggenerated
     */
    private String loanLimitTimeUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.repay_way
     *
     * @mbggenerated
     */
    private String repayWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.contract_num
     *
     * @mbggenerated
     */
    private String contractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.pledge_num
     *
     * @mbggenerated
     */
    private String pledgeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.guaranty_num
     *
     * @mbggenerated
     */
    private String guarantyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.customer_account_num_id
     *
     * @mbggenerated
     */
    private Integer customerAccountNumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.customer_repayment_num_id
     *
     * @mbggenerated
     */
    private Integer customerRepaymentNumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.dept_id
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.is_ended
     *
     * @mbggenerated
     */
    private Boolean isEnded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.ended_at
     *
     * @mbggenerated
     */
    private Date endedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.is_destoryed
     *
     * @mbggenerated
     */
    private Boolean isDestoryed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.destoryed_at
     *
     * @mbggenerated
     */
    private Date destoryedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.is_extended
     *
     * @mbggenerated
     */
    private Boolean isExtended;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.extend_time
     *
     * @mbggenerated
     */
    private Date extendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.extend_loan_id
     *
     * @mbggenerated
     */
    private String extendLoanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.first_repayment_at
     *
     * @mbggenerated
     */
    private Date firstRepaymentAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.withhold_money
     *
     * @mbggenerated
     */
    private BigDecimal withholdMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.is_chargedoff
     *
     * @mbggenerated
     */
    private Boolean isChargedoff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.chargedof_money
     *
     * @mbggenerated
     */
    private BigDecimal chargedofMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.chargedoff_at
     *
     * @mbggenerated
     */
    private Date chargedoffAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.chargedoff_way
     *
     * @mbggenerated
     */
    private String chargedoffWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.create_cm_id
     *
     * @mbggenerated
     */
    private String createCmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.responsible_cm_id
     *
     * @mbggenerated
     */
    private String responsibleCmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.assisted_user_id
     *
     * @mbggenerated
     */
    private String assistedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.applyed_at
     *
     * @mbggenerated
     */
    private Date applyedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.updatedBy
     *
     * @mbggenerated
     */
    private String updatedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.depreciationFee
     *
     * @mbggenerated
     */
    private BigDecimal depreciationFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.drunkDrive
     *
     * @mbggenerated
     */
    private BigDecimal drunkDrive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.cashdepositFee
     *
     * @mbggenerated
     */
    private BigDecimal cashdepositFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.certificatefee
     *
     * @mbggenerated
     */
    private BigDecimal certificatefee;

    /**
     * openId 分销用openId
     */
    private String openId;

    /**
     * 分销用提成比率
     */
    private String openIdrate;

    private String orderid;

    private BigDecimal surplusReimbursementAmount;

    private String pledgeType;
    
    //业务员提成
    private BigDecimal userCommission; 
    
    //分销提成
    private BigDecimal openIdComission;

    //团队经理
    private String teamLeaderId;

    //停车费
    private BigDecimal parkCost;

    //管理费
    private BigDecimal manageCost;

    //按揭车/全款车选择，0：按揭车，1：全款车
    private Integer buy_car_method;

    //还款方案选择，0:方案A，1；方案2
    private Integer plantype;

    private String gpsPattern;

    private String loan_product;

    private BigDecimal gpsCost;
    public BigDecimal getUserCommission() {
		return userCommission;
	}

	public void setUserCommission(BigDecimal userCommission) {
		this.userCommission = userCommission;
	}

	public BigDecimal getOpenIdComission() {
		return openIdComission;
	}

	public void setOpenIdComission(BigDecimal openIdComission) {
		this.openIdComission = openIdComission;
	}

	public String getPledgeType() {
        return pledgeType;
    }

    public void setPledgeType(String pledgeType) {
        this.pledgeType = pledgeType;
    }

    public BigDecimal getSurplusReimbursementAmount() {
        return surplusReimbursementAmount;
    }

    public void setSurplusReimbursementAmount(BigDecimal surplusReimbursementAmount) {
        this.surplusReimbursementAmount = surplusReimbursementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.uuid
     *
     * @return the value of loan_info.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.uuid
     *
     * @param uuid the value for loan_info.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.id
     *
     * @return the value of loan_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.id
     *
     * @param id the value for loan_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }


    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getOpenIdrate() {
        return openIdrate;
    }

    public void setOpenIdrate(String openIdrate) {
        this.openIdrate = openIdrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.customer_id
     *
     * @return the value of loan_info.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.customer_id
     *
     * @param customerId the value for loan_info.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.id_card
     *
     * @return the value of loan_info.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.id_card
     *
     * @param idCard the value for loan_info.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.mobile
     *
     * @return the value of loan_info.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.mobile
     *
     * @param mobile the value for loan_info.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_money
     *
     * @return the value of loan_info.loan_money
     *
     * @mbggenerated
     */
    public BigDecimal getLoanMoney() {
        return loanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_money
     *
     * @param loanMoney the value for loan_info.loan_money
     *
     * @mbggenerated
     */
    public void setLoanMoney(BigDecimal loanMoney) {
        this.loanMoney = loanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.apply_money
     *
     * @return the value of loan_info.apply_money
     *
     * @mbggenerated
     */
    public BigDecimal getApplyMoney() {
        return applyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.apply_money
     *
     * @param applyMoney the value for loan_info.apply_money
     *
     * @mbggenerated
     */
    public void setApplyMoney(BigDecimal applyMoney) {
        this.applyMoney = applyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_type
     *
     * @return the value of loan_info.loan_type
     *
     * @mbggenerated
     */
    public String getLoanType() {
        return loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_type
     *
     * @param loanType the value for loan_info.loan_type
     *
     * @mbggenerated
     */
    public void setLoanType(String loanType) {
        this.loanType = loanType == null ? null : loanType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_status
     *
     * @return the value of loan_info.loan_status
     *
     * @mbggenerated
     */
    public String getLoanStatus() {
        return loanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_status
     *
     * @param loanStatus the value for loan_info.loan_status
     *
     * @mbggenerated
     */
    public void setLoanStatus(String loanStatus) {
        this.loanStatus = loanStatus == null ? null : loanStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_way
     *
     * @return the value of loan_info.loan_way
     *
     * @mbggenerated
     */
    public String getLoanWay() {
        return loanWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_way
     *
     * @param loanWay the value for loan_info.loan_way
     *
     * @mbggenerated
     */
    public void setLoanWay(String loanWay) {
        this.loanWay = loanWay == null ? null : loanWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_purpose
     *
     * @return the value of loan_info.loan_purpose
     *
     * @mbggenerated
     */
    public String getLoanPurpose() {
        return loanPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_purpose
     *
     * @param loanPurpose the value for loan_info.loan_purpose
     *
     * @mbggenerated
     */
    public void setLoanPurpose(String loanPurpose) {
        this.loanPurpose = loanPurpose == null ? null : loanPurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.repay_source
     *
     * @return the value of loan_info.repay_source
     *
     * @mbggenerated
     */
    public String getRepaySource() {
        return repaySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.repay_source
     *
     * @param repaySource the value for loan_info.repay_source
     *
     * @mbggenerated
     */
    public void setRepaySource(String repaySource) {
        this.repaySource = repaySource == null ? null : repaySource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_rate
     *
     * @return the value of loan_info.loan_rate
     *
     * @mbggenerated
     */
    public BigDecimal getLoanRate() {
        return loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_rate
     *
     * @param loanRate the value for loan_info.loan_rate
     *
     * @mbggenerated
     */
    public void setLoanRate(BigDecimal loanRate) {
        this.loanRate = loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_limit_time
     *
     * @return the value of loan_info.loan_limit_time
     *
     * @mbggenerated
     */
    public Integer getLoanLimitTime() {
        return loanLimitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_limit_time
     *
     * @param loanLimitTime the value for loan_info.loan_limit_time
     *
     * @mbggenerated
     */
    public void setLoanLimitTime(Integer loanLimitTime) {
        this.loanLimitTime = loanLimitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_limit_time_unit
     *
     * @return the value of loan_info.loan_limit_time_unit
     *
     * @mbggenerated
     */
    public String getLoanLimitTimeUnit() {
        return loanLimitTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_limit_time_unit
     *
     * @param loanLimitTimeUnit the value for loan_info.loan_limit_time_unit
     *
     * @mbggenerated
     */
    public void setLoanLimitTimeUnit(String loanLimitTimeUnit) {
        this.loanLimitTimeUnit = loanLimitTimeUnit == null ? null : loanLimitTimeUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.repay_way
     *
     * @return the value of loan_info.repay_way
     *
     * @mbggenerated
     */
    public String getRepayWay() {
        return repayWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.repay_way
     *
     * @param repayWay the value for loan_info.repay_way
     *
     * @mbggenerated
     */
    public void setRepayWay(String repayWay) {
        this.repayWay = repayWay == null ? null : repayWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.contract_num
     *
     * @return the value of loan_info.contract_num
     *
     * @mbggenerated
     */
    public String getContractNum() {
        return contractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.contract_num
     *
     * @param contractNum the value for loan_info.contract_num
     *
     * @mbggenerated
     */
    public void setContractNum(String contractNum) {
        this.contractNum = contractNum == null ? null : contractNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.pledge_num
     *
     * @return the value of loan_info.pledge_num
     *
     * @mbggenerated
     */
    public String getPledgeNum() {
        return pledgeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.pledge_num
     *
     * @param pledgeNum the value for loan_info.pledge_num
     *
     * @mbggenerated
     */
    public void setPledgeNum(String pledgeNum) {
        this.pledgeNum = pledgeNum == null ? null : pledgeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.guaranty_num
     *
     * @return the value of loan_info.guaranty_num
     *
     * @mbggenerated
     */
    public String getGuarantyNum() {
        return guarantyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.guaranty_num
     *
     * @param guarantyNum the value for loan_info.guaranty_num
     *
     * @mbggenerated
     */
    public void setGuarantyNum(String guarantyNum) {
        this.guarantyNum = guarantyNum == null ? null : guarantyNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.customer_account_num_id
     *
     * @return the value of loan_info.customer_account_num_id
     *
     * @mbggenerated
     */
    public Integer getCustomerAccountNumId() {
        return customerAccountNumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.customer_account_num_id
     *
     * @param customerAccountNumId the value for loan_info.customer_account_num_id
     *
     * @mbggenerated
     */
    public void setCustomerAccountNumId(Integer customerAccountNumId) {
        this.customerAccountNumId = customerAccountNumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.customer_repayment_num_id
     *
     * @return the value of loan_info.customer_repayment_num_id
     *
     * @mbggenerated
     */
    public Integer getCustomerRepaymentNumId() {
        return customerRepaymentNumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.customer_repayment_num_id
     *
     * @param customerRepaymentNumId the value for loan_info.customer_repayment_num_id
     *
     * @mbggenerated
     */
    public void setCustomerRepaymentNumId(Integer customerRepaymentNumId) {
        this.customerRepaymentNumId = customerRepaymentNumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.dept_id
     *
     * @return the value of loan_info.dept_id
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.dept_id
     *
     * @param deptId the value for loan_info.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.company_id
     *
     * @return the value of loan_info.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.company_id
     *
     * @param companyId the value for loan_info.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.is_ended
     *
     * @return the value of loan_info.is_ended
     *
     * @mbggenerated
     */
    public Boolean getIsEnded() {
        return isEnded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.is_ended
     *
     * @param isEnded the value for loan_info.is_ended
     *
     * @mbggenerated
     */
    public void setIsEnded(Boolean isEnded) {
        this.isEnded = isEnded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.ended_at
     *
     * @return the value of loan_info.ended_at
     *
     * @mbggenerated
     */
    public Date getEndedAt() {
        return endedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.ended_at
     *
     * @param endedAt the value for loan_info.ended_at
     *
     * @mbggenerated
     */
    public void setEndedAt(Date endedAt) {
        this.endedAt = endedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.is_destoryed
     *
     * @return the value of loan_info.is_destoryed
     *
     * @mbggenerated
     */
    public Boolean getIsDestoryed() {
        return isDestoryed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.is_destoryed
     *
     * @param isDestoryed the value for loan_info.is_destoryed
     *
     * @mbggenerated
     */
    public void setIsDestoryed(Boolean isDestoryed) {
        this.isDestoryed = isDestoryed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.destoryed_at
     *
     * @return the value of loan_info.destoryed_at
     *
     * @mbggenerated
     */
    public Date getDestoryedAt() {
        return destoryedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.destoryed_at
     *
     * @param destoryedAt the value for loan_info.destoryed_at
     *
     * @mbggenerated
     */
    public void setDestoryedAt(Date destoryedAt) {
        this.destoryedAt = destoryedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.is_extended
     *
     * @return the value of loan_info.is_extended
     *
     * @mbggenerated
     */
    public Boolean getIsExtended() {
        return isExtended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.is_extended
     *
     * @param isExtended the value for loan_info.is_extended
     *
     * @mbggenerated
     */
    public void setIsExtended(Boolean isExtended) {
        this.isExtended = isExtended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.extend_time
     *
     * @return the value of loan_info.extend_time
     *
     * @mbggenerated
     */
    public Date getExtendTime() {
        return extendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.extend_time
     *
     * @param extendTime the value for loan_info.extend_time
     *
     * @mbggenerated
     */
    public void setExtendTime(Date extendTime) {
        this.extendTime = extendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.extend_loan_id
     *
     * @return the value of loan_info.extend_loan_id
     *
     * @mbggenerated
     */
    public String getExtendLoanId() {
        return extendLoanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.extend_loan_id
     *
     * @param extendLoanId the value for loan_info.extend_loan_id
     *
     * @mbggenerated
     */
    public void setExtendLoanId(String extendLoanId) {
        this.extendLoanId = extendLoanId == null ? null : extendLoanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.first_repayment_at
     *
     * @return the value of loan_info.first_repayment_at
     *
     * @mbggenerated
     */
    public Date getFirstRepaymentAt() {
        return firstRepaymentAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.first_repayment_at
     *
     * @param firstRepaymentAt the value for loan_info.first_repayment_at
     *
     * @mbggenerated
     */
    public void setFirstRepaymentAt(Date firstRepaymentAt) {
        this.firstRepaymentAt = firstRepaymentAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.withhold_money
     *
     * @return the value of loan_info.withhold_money
     *
     * @mbggenerated
     */
    public BigDecimal getWithholdMoney() {
        return withholdMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.withhold_money
     *
     * @param withholdMoney the value for loan_info.withhold_money
     *
     * @mbggenerated
     */
    public void setWithholdMoney(BigDecimal withholdMoney) {
        this.withholdMoney = withholdMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.is_chargedoff
     *
     * @return the value of loan_info.is_chargedoff
     *
     * @mbggenerated
     */
    public Boolean getIsChargedoff() {
        return isChargedoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.is_chargedoff
     *
     * @param isChargedoff the value for loan_info.is_chargedoff
     *
     * @mbggenerated
     */
    public void setIsChargedoff(Boolean isChargedoff) {
        this.isChargedoff = isChargedoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.chargedof_money
     *
     * @return the value of loan_info.chargedof_money
     *
     * @mbggenerated
     */
    public BigDecimal getChargedofMoney() {
        return chargedofMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.chargedof_money
     *
     * @param chargedofMoney the value for loan_info.chargedof_money
     *
     * @mbggenerated
     */
    public void setChargedofMoney(BigDecimal chargedofMoney) {
        this.chargedofMoney = chargedofMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.chargedoff_at
     *
     * @return the value of loan_info.chargedoff_at
     *
     * @mbggenerated
     */
    public Date getChargedoffAt() {
        return chargedoffAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.chargedoff_at
     *
     * @param chargedoffAt the value for loan_info.chargedoff_at
     *
     * @mbggenerated
     */
    public void setChargedoffAt(Date chargedoffAt) {
        this.chargedoffAt = chargedoffAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.chargedoff_way
     *
     * @return the value of loan_info.chargedoff_way
     *
     * @mbggenerated
     */
    public String getChargedoffWay() {
        return chargedoffWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.chargedoff_way
     *
     * @param chargedoffWay the value for loan_info.chargedoff_way
     *
     * @mbggenerated
     */
    public void setChargedoffWay(String chargedoffWay) {
        this.chargedoffWay = chargedoffWay == null ? null : chargedoffWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.create_cm_id
     *
     * @return the value of loan_info.create_cm_id
     *
     * @mbggenerated
     */
    public String getCreateCmId() {
        return createCmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.create_cm_id
     *
     * @param createCmId the value for loan_info.create_cm_id
     *
     * @mbggenerated
     */
    public void setCreateCmId(String createCmId) {
        this.createCmId = createCmId == null ? null : createCmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.responsible_cm_id
     *
     * @return the value of loan_info.responsible_cm_id
     *
     * @mbggenerated
     */
    public String getResponsibleCmId() {
        return responsibleCmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.responsible_cm_id
     *
     * @param responsibleCmId the value for loan_info.responsible_cm_id
     *
     * @mbggenerated
     */
    public void setResponsibleCmId(String responsibleCmId) {
        this.responsibleCmId = responsibleCmId == null ? null : responsibleCmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.assisted_user_id
     *
     * @return the value of loan_info.assisted_user_id
     *
     * @mbggenerated
     */
    public String getAssistedUserId() {
        return assistedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.assisted_user_id
     *
     * @param assistedUserId the value for loan_info.assisted_user_id
     *
     * @mbggenerated
     */
    public void setAssistedUserId(String assistedUserId) {
        this.assistedUserId = assistedUserId == null ? null : assistedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.applyed_at
     *
     * @return the value of loan_info.applyed_at
     *
     * @mbggenerated
     */
    public Date getApplyedAt() {
        return applyedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.applyed_at
     *
     * @param applyedAt the value for loan_info.applyed_at
     *
     * @mbggenerated
     */
    public void setApplyedAt(Date applyedAt) {
        this.applyedAt = applyedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.created_at
     *
     * @return the value of loan_info.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.created_at
     *
     * @param createdAt the value for loan_info.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.updatedBy
     *
     * @return the value of loan_info.updatedBy
     *
     * @mbggenerated
     */
    public String getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.updatedBy
     *
     * @param updatedby the value for loan_info.updatedBy
     *
     * @mbggenerated
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby == null ? null : updatedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.updated_at
     *
     * @return the value of loan_info.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.updated_at
     *
     * @param updatedAt the value for loan_info.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }


    public String getProcessinsId() {
        return processinsId;
    }

    public void setProcessinsId(String processinsId) {
        this.processinsId = processinsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.depreciationFee
     *
     * @return the value of loan_info.depreciationFee
     *
     * @mbggenerated
     */
    public BigDecimal getDepreciationFee() {
        return depreciationFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.depreciationFee
     *
     * @param depreciationfee the value for loan_info.depreciationFee
     *
     * @mbggenerated
     */
    public void setDepreciationFee(BigDecimal depreciationFee) {
        this.depreciationFee = depreciationFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.drunkDrive
     *
     * @return the value of loan_info.drunkDrive
     *
     * @mbggenerated
     */
    public BigDecimal getDrunkDrive() {
        return drunkDrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.drunkDrive
     *
     * @param drunkdrive the value for loan_info.drunkDrive
     *
     * @mbggenerated
     */
    public void setDrunkDrive(BigDecimal drunkdrive) {
        this.drunkDrive = drunkdrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.cashdepositFee
     *
     * @return the value of loan_info.cashdepositFee
     *
     * @mbggenerated
     */
    public BigDecimal getCashdepositFee() {
        return cashdepositFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.cashdepositFee
     *
     * @param cashdepositfee the value for loan_info.cashdepositFee
     *
     * @mbggenerated
     */
    public void setCashdepositFee(BigDecimal cashdepositFee) {
        this.cashdepositFee = cashdepositFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.certificatefee
     *
     * @return the value of loan_info.certificatefee
     *
     * @mbggenerated
     */
    public BigDecimal getCertificatefee() {
        return certificatefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.certificatefee
     *
     * @param certificatefee the value for loan_info.certificatefee
     *
     * @mbggenerated
     */
    public void setCertificatefee(BigDecimal certificatefee) {
        this.certificatefee = certificatefee;
    }

    @Override
    public String toString() {
        return "LoanInfo{" +
                "uuid='" + uuid + '\'' +
                ", id=" + id +
                ", customerId='" + customerId + '\'' +
                ", idCard='" + idCard + '\'' +
                ", mobile='" + mobile + '\'' +
                ", loanMoney=" + loanMoney +
                ", applyMoney=" + applyMoney +
                ", loanType='" + loanType + '\'' +
                ", loanStatus='" + loanStatus + '\'' +
                ", loanWay='" + loanWay + '\'' +
                ", loanPurpose='" + loanPurpose + '\'' +
                ", repaySource='" + repaySource + '\'' +
                ", loanRate=" + loanRate +
                ", loanLimitTime=" + loanLimitTime +
                ", loanLimitTimeUnit='" + loanLimitTimeUnit + '\'' +
                ", repayWay='" + repayWay + '\'' +
                ", contractNum='" + contractNum + '\'' +
                ", pledgeNum='" + pledgeNum + '\'' +
                ", guarantyNum='" + guarantyNum + '\'' +
                ", customerAccountNumId=" + customerAccountNumId +
                ", customerRepaymentNumId=" + customerRepaymentNumId +
                ", deptId=" + deptId +
                ", companyId=" + companyId +
                ", isEnded=" + isEnded +
                ", endedAt=" + endedAt +
                ", isDestoryed=" + isDestoryed +
                ", destoryedAt=" + destoryedAt +
                ", isExtended=" + isExtended +
                ", extendTime=" + extendTime +
                ", extendLoanId='" + extendLoanId + '\'' +
                ", firstRepaymentAt=" + firstRepaymentAt +
                ", withholdMoney=" + withholdMoney +
                ", isChargedoff=" + isChargedoff +
                ", chargedofMoney=" + chargedofMoney +
                ", chargedoffAt=" + chargedoffAt +
                ", chargedoffWay='" + chargedoffWay + '\'' +
                ", createCmId='" + createCmId + '\'' +
                ", responsibleCmId='" + responsibleCmId + '\'' +
                ", assistedUserId='" + assistedUserId + '\'' +
                ", applyedAt=" + applyedAt +
                ", createdAt=" + createdAt +
                ", updatedby='" + updatedby + '\'' +
                ", updatedAt=" + updatedAt +
                ", depreciationfee=" + depreciationFee +
                ", drunkdrive=" + drunkDrive +
                ", cashdepositfee=" + cashdepositFee +
                ", certificatefee=" + certificatefee +
                ", teamLeaderId=" + teamLeaderId +
                ", parkCost=" + parkCost +
                ", manageCost=" + manageCost +
                '}';
    }

    /**
     * 订单ID
     */
    public String getOrderid() {
        return orderid;
    }

    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    public String getTeamLeaderId() {
        return teamLeaderId;
    }

    public void setTeamLeaderId(String teamLeaderId) {
        this.teamLeaderId = teamLeaderId;
    }

    public BigDecimal getParkCost() {
        return parkCost;
    }

    public void setParkCost(BigDecimal parkCost) {
        this.parkCost = parkCost;
    }

    public BigDecimal getManageCost() {
        return manageCost;
    }

    public void setManageCost(BigDecimal manageCost) {
        this.manageCost = manageCost;
    }

    public Integer getBuy_car_method() {
        return buy_car_method;
    }

    public void setBuy_car_method(Integer buy_car_method) {
        this.buy_car_method = buy_car_method;
    }

    public Integer getPlantype() {
        return plantype;
    }

    public void setPlantype(Integer plantype) {
        this.plantype = plantype;
    }

    public String getGpsPattern() {
        return gpsPattern;
    }

    public void setGpsPattern(String gpsPattern) {
        this.gpsPattern = gpsPattern;
    }

    public String getLoan_product() {
        return loan_product;
    }

    public void setLoan_product(String loan_product) {
        this.loan_product = loan_product;
    }

    public BigDecimal getGpsCost() {
        return gpsCost;
    }

    public void setGpsCost(BigDecimal gpsCost) {
        this.gpsCost = gpsCost;
    }
}