package com.utonw.dealer.api.entity.erp;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.activiti.engine.runtime.ProcessInstance;

import java.io.Serializable;

public class LoanInfoWithBLOBs extends LoanInfo implements Serializable {
    private static final long serialVersionUID = 6147480356056575259L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.host_opinion
     *
     * @mbggenerated
     */
    private String hostOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.assisted_opinion
     *
     * @mbggenerated
     */
    private String assistedOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.remark
     *
     * @mbggenerated
     */
    private String remark;


    @JsonIgnore
    private ProcessInstance processions;


    private CustomerRegisterInfo customerRegisterInfo;
    private GuaranteeEvaluateInfo guaranteeEvaluateInfo;
    private User createBy;
    private User responsibleBy;
    private Dept dept;
    private Company company;
    private RepayPlan repayPlan;
    private RepayPlanDetail repayPlanDetail;
    private CustomerAccountInfo customerAccountInfo;
    private User principalName;
    private String reviewedBy;
    

	public String getReviewedBy() {
		return reviewedBy;
	}

	public void setReviewedBy(String reviewedBy) {
		this.reviewedBy = reviewedBy;
	}

	public User getPrincipalName() {
		return principalName;
	}

	public void setPrincipalName(User principalName) {
		this.principalName = principalName;
	}

	public CustomerAccountInfo getCustomerAccountInfo() {
        return customerAccountInfo;
    }

    public void setCustomerAccountInfo(CustomerAccountInfo customerAccountInfo) {
        this.customerAccountInfo = customerAccountInfo;
    }


    public RepayPlan getRepayPlan() {
        return repayPlan;
    }

    public void setRepayPlan(RepayPlan repayPlan) {
        this.repayPlan = repayPlan;
    }

    public RepayPlanDetail getRepayPlanDetail() {
        return repayPlanDetail;
    }

    public void setRepayPlanDetail(RepayPlanDetail repayPlanDetail) {
        this.repayPlanDetail = repayPlanDetail;
    }

    public ProcessInstance getProcessions() {
        return processions;
    }

    public void setProcessions(ProcessInstance processions) {
        this.processions = processions;
    }

    public CustomerRegisterInfo getCustomerRegisterInfo() {
        return customerRegisterInfo;
    }

    public void setCustomerRegisterInfo(CustomerRegisterInfo customerRegisterInfo) {
        this.customerRegisterInfo = customerRegisterInfo;
    }

    public GuaranteeEvaluateInfo getGuaranteeEvaluateInfo() {
        return guaranteeEvaluateInfo;
    }

    public void setGuaranteeEvaluateInfo(GuaranteeEvaluateInfo guaranteeEvaluateInfo) {
        this.guaranteeEvaluateInfo = guaranteeEvaluateInfo;
    }

    public User getCreateBy() {
        return createBy;
    }

    public void setCreateBy(User createBy) {
        this.createBy = createBy;
    }

    public User getResponsibleBy() {
        return responsibleBy;
    }

    public void setResponsibleBy(User responsibleBy) {
        this.responsibleBy = responsibleBy;
    }

    public Dept getDept() {
        return dept;
    }

    public void setDept(Dept dept) {
        this.dept = dept;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.host_opinion
     *
     * @return the value of loan_info.host_opinion
     * @mbggenerated
     */
    public String getHostOpinion() {
        return hostOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.host_opinion
     *
     * @param hostOpinion the value for loan_info.host_opinion
     * @mbggenerated
     */
    public void setHostOpinion(String hostOpinion) {
        this.hostOpinion = hostOpinion == null ? null : hostOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.assisted_opinion
     *
     * @return the value of loan_info.assisted_opinion
     * @mbggenerated
     */
    public String getAssistedOpinion() {
        return assistedOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.assisted_opinion
     *
     * @param assistedOpinion the value for loan_info.assisted_opinion
     * @mbggenerated
     */
    public void setAssistedOpinion(String assistedOpinion) {
        this.assistedOpinion = assistedOpinion == null ? null : assistedOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.remark
     *
     * @return the value of loan_info.remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.remark
     *
     * @param remark the value for loan_info.remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }


	@Override
    public String toString() {
        return "LoanInfoWithBLOBs{" +
                "hostOpinion='" + hostOpinion + '\'' +
                ", assistedOpinion='" + assistedOpinion + '\'' +
                ", remark='" + remark + '\'' +
                "} " + super.toString();
    }
}