package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;
import java.util.Date;

public class LoanInfoAttachment implements Serializable {
    private static final long serialVersionUID = 6040815201074341545L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.loan_id
     *
     * @mbggenerated
     */
    private String loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.attachment_type
     *
     * @mbggenerated
     */
    private String attachmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.attachment_title
     *
     * @mbggenerated
     */
    private String attachmentTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.attachment_thumb
     *
     * @mbggenerated
     */
    private String attachmentThumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.attachment_path
     *
     * @mbggenerated
     */
    private String attachmentPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.is_valid
     *
     * @mbggenerated
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.uploaded_by
     *
     * @mbggenerated
     */
    private String uploadedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info_attachment.uploaded_at
     *
     * @mbggenerated
     */
    private Date uploadedAt;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.id
     *
     * @return the value of loan_info_attachment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.id
     *
     * @param id the value for loan_info_attachment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.loan_id
     *
     * @return the value of loan_info_attachment.loan_id
     *
     * @mbggenerated
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.loan_id
     *
     * @param loanId the value for loan_info_attachment.loan_id
     *
     * @mbggenerated
     */
    public void setLoanId(String loanId) {
        this.loanId = loanId == null ? null : loanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.attachment_type
     *
     * @return the value of loan_info_attachment.attachment_type
     *
     * @mbggenerated
     */
    public String getAttachmentType() {
        return attachmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.attachment_type
     *
     * @param attachmentType the value for loan_info_attachment.attachment_type
     *
     * @mbggenerated
     */
    public void setAttachmentType(String attachmentType) {
        this.attachmentType = attachmentType == null ? null : attachmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.attachment_title
     *
     * @return the value of loan_info_attachment.attachment_title
     *
     * @mbggenerated
     */
    public String getAttachmentTitle() {
        return attachmentTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.attachment_title
     *
     * @param attachmentTitle the value for loan_info_attachment.attachment_title
     *
     * @mbggenerated
     */
    public void setAttachmentTitle(String attachmentTitle) {
        this.attachmentTitle = attachmentTitle == null ? null : attachmentTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.attachment_thumb
     *
     * @return the value of loan_info_attachment.attachment_thumb
     *
     * @mbggenerated
     */
    public String getAttachmentThumb() {
        return attachmentThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.attachment_thumb
     *
     * @param attachmentThumb the value for loan_info_attachment.attachment_thumb
     *
     * @mbggenerated
     */
    public void setAttachmentThumb(String attachmentThumb) {
        this.attachmentThumb = attachmentThumb == null ? null : attachmentThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.attachment_path
     *
     * @return the value of loan_info_attachment.attachment_path
     *
     * @mbggenerated
     */
    public String getAttachmentPath() {
        return attachmentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.attachment_path
     *
     * @param attachmentPath the value for loan_info_attachment.attachment_path
     *
     * @mbggenerated
     */
    public void setAttachmentPath(String attachmentPath) {
        this.attachmentPath = attachmentPath == null ? null : attachmentPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.is_valid
     *
     * @return the value of loan_info_attachment.is_valid
     *
     * @mbggenerated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.is_valid
     *
     * @param isValid the value for loan_info_attachment.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.uploaded_by
     *
     * @return the value of loan_info_attachment.uploaded_by
     *
     * @mbggenerated
     */
    public String getUploadedBy() {
        return uploadedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.uploaded_by
     *
     * @param uploadedBy the value for loan_info_attachment.uploaded_by
     *
     * @mbggenerated
     */
    public void setUploadedBy(String uploadedBy) {
        this.uploadedBy = uploadedBy == null ? null : uploadedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info_attachment.uploaded_at
     *
     * @return the value of loan_info_attachment.uploaded_at
     *
     * @mbggenerated
     */
    public Date getUploadedAt() {
        return uploadedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info_attachment.uploaded_at
     *
     * @param uploadedAt the value for loan_info_attachment.uploaded_at
     *
     * @mbggenerated
     */
    public void setUploadedAt(Date uploadedAt) {
        this.uploadedAt = uploadedAt;
    }
}