package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;

public class ModuleManage implements Serializable {

    private static final long serialVersionUID = 7346613347664737080L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_manage.module_id
     *
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_manage.module_name
     *
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_manage.module_url
     *
     */
    private String moduleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_manage.module_parent_id
     *
     */
    private Integer moduleParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_manage.module_seq
     *
     */
    private Integer moduleSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_manage.module_icon
     *
     */
    private String moduleIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_manage.module_type
     *
     */
    private Integer moduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_manage.module_describe
     *
     */
    private String moduleDescribe;

    private String module_menu_id;
    private String module_icon_class;
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_manage.module_id
     *
     * @param moduleId the value for module_manage.module_id
     * 
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_manage.module_name
     *
     * @return the value of module_manage.module_name
     * 
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_manage.module_name
     *
     * @param moduleName the value for module_manage.module_name
     * 
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_manage.module_url
     *
     * @return the value of module_manage.module_url
     * 
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_manage.module_url
     *
     * @param moduleUrl the value for module_manage.module_url
     * 
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_manage.module_parent_id
     *
     * @return the value of module_manage.module_parent_id
     * 
     */
    public Integer getModuleParentId() {
        return moduleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_manage.module_parent_id
     *
     * @param moduleParentId the value for module_manage.module_parent_id
     * 
     */
    public void setModuleParentId(Integer moduleParentId) {
        this.moduleParentId = moduleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_manage.module_seq
     *
     * @return the value of module_manage.module_seq
     * 
     */
    public Integer getModuleSeq() {
        return moduleSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_manage.module_seq
     *
     * @param moduleSeq the value for module_manage.module_seq
     * 
     */
    public void setModuleSeq(Integer moduleSeq) {
        this.moduleSeq = moduleSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_manage.module_icon
     *
     * @return the value of module_manage.module_icon
     * 
     */
    public String getModuleIcon() {
        return moduleIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_manage.module_icon
     *
     * @param moduleIcon the value for module_manage.module_icon
     * 
     */
    public void setModuleIcon(String moduleIcon) {
        this.moduleIcon = moduleIcon == null ? null : moduleIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_manage.module_type
     *
     * @return the value of module_manage.module_type
     * 
     */
    public Integer getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_manage.module_type
     *
     * @param moduleType the value for module_manage.module_type
     * 
     */
    public void setModuleType(Integer moduleType) {
        this.moduleType = moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_manage.module_describe
     *
     * @return the value of module_manage.module_describe
     * 
     */
    public String getModuleDescribe() {
        return moduleDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_manage.module_describe
     *
     * @param moduleDescribe the value for module_manage.module_describe
     * 
     */
    public void setModuleDescribe(String moduleDescribe) {
        this.moduleDescribe = moduleDescribe == null ? null : moduleDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_manage.module_id
     *
     * @return the value of module_manage.module_id
     *
     */
    public String getModule_menu_id() {
        return module_menu_id;
    }
    public void setModule_menu_id(String module_menu_id) {
        this.module_menu_id = module_menu_id;
    }
    public String getModule_icon_class() {
        return module_icon_class;
    }
    public void setModule_icon_class(String module_icon_class) {
        this.module_icon_class = module_icon_class;
    }
}