package com.utonw.dealer.api.entity.erp;

import java.beans.Transient;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Repayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.loanId
     *
     * @mbggenerated
     */
    private String loanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.repaymentImagUrl
     *
     * @mbggenerated
     */
    private String repaymentimagurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.replanDetaiId
     *
     * @mbggenerated
     */
    private String replandetaiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.transactionId
     *
     * @mbggenerated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment.updateDate
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * 还款计划明细
     */
    private RepayPlanDetail repayPlanDetail;

    /**
     * 罚息
     */
    private BigDecimal fineFee;

    /**
     * 最低还款额
     */
    private BigDecimal minPay;

    /**
     * 实际还款总额合计
     */
    private BigDecimal countSum;

    /**
     * 逾期天数
     */
    private Integer overdueDay;

    /**
     * 还款方式
     */
    private String repaymentType;

    /**
     * gps费用合计
     */
    private BigDecimal gpsCostFeeSum;


    /**
     * 管理费用合计
     */
    private BigDecimal manageFeeSum;


    /**
     * 还款明细
     */
    private List<RepaymentTransaction> repaymentTransactions;
    private RepaymentTransaction repaymentTransactionss;
    public RepaymentTransaction getRepaymentTransaction() {
		return repaymentTransactionss;
	}

	public void setRepaymentTransaction(RepaymentTransaction repaymentTransaction) {
		this.repaymentTransactionss = repaymentTransaction;
	}

	/**
     * 流程实例Id
     */
    private String processinsId;

    private String is_overdue;

    private Date updateDay;

    private List<PaymentHistory> paymentHistoryList;
    
    
    public List<PaymentHistory> getPaymentHistoryList() {
		return paymentHistoryList;
	}

	public void setPaymentHistoryList(List<PaymentHistory> paymentHistoryList) {
		this.paymentHistoryList = paymentHistoryList;
	}

	public String getProcessinsId() {
        return processinsId;
    }

    public void setProcessinsId(String processinsId) {
        this.processinsId = processinsId;
    }

    private LoanInfoAttachment loanInfoAttachment;

    public LoanInfoAttachment getLoanInfoAttachment() {
        return loanInfoAttachment;
    }

    public void setLoanInfoAttachment(LoanInfoAttachment loanInfoAttachment) {
        this.loanInfoAttachment = loanInfoAttachment;
    }

    public String getRepaymentType() {
        return repaymentType;
    }


    public void setRepaymentType(String repaymentType) {
        this.repaymentType = repaymentType;
    }

    @Transient
    public Integer getOverdueDay() {
        return overdueDay;
    }

    public void setOverdueDay(Integer overdueDay) {
        this.overdueDay = overdueDay;
    }

    @Transient
    public BigDecimal getMinPay() {
        return minPay;
    }

    public void setMinPay(BigDecimal minPay) {
        this.minPay = minPay;
    }

    @Transient
    public BigDecimal getCountSum() {
        return countSum;
    }

    public void setCountSum(BigDecimal countSum) {
        this.countSum = countSum;
    }

    @Transient
    public BigDecimal getFineFee() {
        return fineFee;
    }

    public void setFineFee(BigDecimal fineFee) {
        this.fineFee = fineFee;
    }

    public List<RepaymentTransaction> getRepaymentTransactions() {
        return repaymentTransactions;
    }

    public void setRepaymentTransactions(List<RepaymentTransaction> repaymentTransactions) {
        this.repaymentTransactions = repaymentTransactions;
    }

    @Transient
    public RepayPlanDetail getRepayPlanDetail() {
        return repayPlanDetail;
    }

    public void setRepayPlanDetail(RepayPlanDetail repayPlanDetail) {
        this.repayPlanDetail = repayPlanDetail;
    }


    @Transient
    public BigDecimal getGpsCostFeeSum() {
        return gpsCostFeeSum;
    }

    public void setGpsCostFeeSum(BigDecimal gpsCostFeeSum) {
        this.gpsCostFeeSum = gpsCostFeeSum;
    }

    @Transient
    public BigDecimal getManageFeeSum() {
        return manageFeeSum;
    }

    public void setManageFeeSum(BigDecimal manageFeeSum) {
        this.manageFeeSum = manageFeeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.uuid
     *
     * @return the value of repayment.uuid
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.uuid
     *
     * @param uuid the value for repayment.uuid
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.id
     *
     * @return the value of repayment.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.id
     *
     * @param id the value for repayment.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.loanId
     *
     * @return the value of repayment.loanId
     * @mbggenerated
     */
    public String getLoanid() {
        return loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.loanId
     *
     * @param loanid the value for repayment.loanId
     * @mbggenerated
     */
    public void setLoanid(String loanid) {
        this.loanid = loanid == null ? null : loanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.repaymentImagUrl
     *
     * @return the value of repayment.repaymentImagUrl
     * @mbggenerated
     */
    public String getRepaymentimagurl() {
        return repaymentimagurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.repaymentImagUrl
     *
     * @param repaymentimagurl the value for repayment.repaymentImagUrl
     * @mbggenerated
     */
    public void setRepaymentimagurl(String repaymentimagurl) {
        this.repaymentimagurl = repaymentimagurl == null ? null : repaymentimagurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.replanDetaiId
     *
     * @return the value of repayment.replanDetaiId
     * @mbggenerated
     */
    public String getReplandetaiid() {
        return replandetaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.replanDetaiId
     *
     * @param replandetaiid the value for repayment.replanDetaiId
     * @mbggenerated
     */
    public void setReplandetaiid(String replandetaiid) {
        this.replandetaiid = replandetaiid == null ? null : replandetaiid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.transactionId
     *
     * @return the value of repayment.transactionId
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.transactionId
     *
     * @param transactionid the value for repayment.transactionId
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.status
     *
     * @return the value of repayment.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.status
     *
     * @param status the value for repayment.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.remark
     *
     * @return the value of repayment.remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.remark
     *
     * @param remark the value for repayment.remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.name
     *
     * @return the value of repayment.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.name
     *
     * @param name the value for repayment.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.createDate
     *
     * @return the value of repayment.createDate
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.createDate
     *
     * @param createdate the value for repayment.createDate
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment.updateDate
     *
     * @return the value of repayment.updateDate
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment.updateDate
     *
     * @param updatedate the value for repayment.updateDate
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public Date getUpdateDay() { return updateDay; }

    public void setUpdateDay(Date updateDay) { this.updateDay = updateDay; }

    @Override
    public String toString() {
        return "Repayment{" +
                "uuid='" + uuid + '\'' +
                ", id=" + id +
                ", loanid='" + loanid + '\'' +
                ", repaymentimagurl='" + repaymentimagurl + '\'' +
                ", replandetaiid='" + replandetaiid + '\'' +
                ", status=" + status +
                ", remark='" + remark + '\'' +
                ", name='" + name + '\'' +
                ", createdate=" + createdate +
                ", updatedate=" + updatedate +
                ", repayPlanDetail=" + repayPlanDetail +
                ", fineFee=" + fineFee +
                ", minPay=" + minPay +
                ", countSum=" + countSum +
                ", overdueDay=" + overdueDay +
                ", repaymentType='" + repaymentType + '\'' +
                ", gpsCostFeeSum=" + gpsCostFeeSum +
                ", manageFeeSum=" + manageFeeSum +
                '}';
    }

    /**
     * 是否是逾期状态
     */
    public String getIs_overdue() {
        return is_overdue;
    }

    public void setIs_overdue(String is_overdue) {
        this.is_overdue = is_overdue;
    }
}