package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;
import java.util.List;

public class RepayPlan implements Serializable {
    private static final long serialVersionUID = 8583588611737182296L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan.duration
     *
     * @mbggenerated
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan.loanId
     *
     * @mbggenerated
     */
    private String loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan.productName
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan.repayType
     *
     * @mbggenerated
     */
    private String repayType;

    private List<RepayPlanDetail> repayPlanDetailList;

    public List<RepayPlanDetail> getRepayPlanDetailList() {
        return repayPlanDetailList;
    }

    public void setRepayPlanDetailList(List<RepayPlanDetail> repayPlanDetailList) {
        this.repayPlanDetailList = repayPlanDetailList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan.id
     *
     * @return the value of repayplan.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan.id
     *
     * @param id the value for repayplan.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan.duration
     *
     * @return the value of repayplan.duration
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan.duration
     *
     * @param duration the value for repayplan.duration
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan.loanId
     *
     * @return the value of repayplan.loanId
     *
     * @mbggenerated
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan.loanId
     *
     * @param loanId the value for repayplan.loanId
     *
     * @mbggenerated
     */
    public void setLoanId(String loanId) {
        this.loanId = loanId == null ? null : loanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan.productName
     *
     * @return the value of repayplan.productName
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan.productName
     *
     * @param productName the value for repayplan.productName
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan.repayType
     *
     * @return the value of repayplan.repayType
     *
     * @mbggenerated
     */
    public String getRepayType() {
        return repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan.repayType
     *
     * @param repayType the value for repayplan.repayType
     *
     * @mbggenerated
     */
    public void setRepayType(String repayType) {
        this.repayType = repayType == null ? null : repayType.trim();
    }
}