package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;

public class RoleUser implements Serializable {
    private static final long serialVersionUID = -4706083727743440662L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.rb_id
     *
     */
    private Integer rbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.rb_role_id
     *
     */
    private Integer rbRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.rb_user_id
     *
     */
    private String rbUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.rb_id
     *
     * @return the value of role_user.rb_id
     */
    public Integer getRbId() {
        return rbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.rb_id
     *
     * @param rbId the value for role_user.rb_id
     */
    public void setRbId(Integer rbId) {
        this.rbId = rbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.rb_role_id
     *
     * @return the value of role_user.rb_role_id
     */
    public Integer getRbRoleId() {
        return rbRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.rb_role_id
     *
     * @param rbRoleId the value for role_user.rb_role_id
     */
    public void setRbRoleId(Integer rbRoleId) {
        this.rbRoleId = rbRoleId;
    }

    public String getRbUserId() {
        return rbUserId;
    }

    public void setRbUserId(String rbUserId) {
        this.rbUserId = rbUserId;
    }
}