package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;

public class RoleManage implements Serializable {
    private static final long serialVersionUID = 9210064789957959765L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_manage.role_id
     *
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_manage.role_name
     *
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_manage.is_show
     *
     */
    private String isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_manage.role_id
     *
     * @return the value of role_manage.role_id
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_manage.role_id
     *
     * @param roleId the value for role_manage.role_id
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_manage.role_name
     *
     * @return the value of role_manage.role_name
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_manage.role_name
     *
     * @param roleName the value for role_manage.role_name
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_manage.is_show
     *
     * @return the value of role_manage.is_show
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_manage.is_show
     *
     * @param isShow the value for role_manage.is_show
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }
}