package com.utonw.dealer.api.entity.erp;

import java.io.Serializable;

public class TodoDefineEntity  implements Serializable {
    private static final long serialVersionUID = 8037697096748548183L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tododefine.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tododefine.business
     *
     * @mbggenerated
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tododefine.businesskeyname
     *
     * @mbggenerated
     */
    private String businesskeyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tododefine.businessvalue
     *
     * @mbggenerated
     */
    private String businessvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tododefine.tablename
     *
     * @mbggenerated
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tododefine.property
     *
     * @mbggenerated
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tododefine.property2
     *
     * @mbggenerated
     */
    private String property2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tododefine.ID
     *
     * @return the value of t_tododefine.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tododefine.ID
     *
     * @param id the value for t_tododefine.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tododefine.business
     *
     * @return the value of t_tododefine.business
     *
     * @mbggenerated
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tododefine.business
     *
     * @param business the value for t_tododefine.business
     *
     * @mbggenerated
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tododefine.businesskeyname
     *
     * @return the value of t_tododefine.businesskeyname
     *
     * @mbggenerated
     */
    public String getBusinesskeyname() {
        return businesskeyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tododefine.businesskeyname
     *
     * @param businesskeyname the value for t_tododefine.businesskeyname
     *
     * @mbggenerated
     */
    public void setBusinesskeyname(String businesskeyname) {
        this.businesskeyname = businesskeyname == null ? null : businesskeyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tododefine.businessvalue
     *
     * @return the value of t_tododefine.businessvalue
     *
     * @mbggenerated
     */
    public String getBusinessvalue() {
        return businessvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tododefine.businessvalue
     *
     * @param businessvalue the value for t_tododefine.businessvalue
     *
     * @mbggenerated
     */
    public void setBusinessvalue(String businessvalue) {
        this.businessvalue = businessvalue == null ? null : businessvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tododefine.tablename
     *
     * @return the value of t_tododefine.tablename
     *
     * @mbggenerated
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tododefine.tablename
     *
     * @param tablename the value for t_tododefine.tablename
     *
     * @mbggenerated
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tododefine.property
     *
     * @return the value of t_tododefine.property
     *
     * @mbggenerated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tododefine.property
     *
     * @param property the value for t_tododefine.property
     *
     * @mbggenerated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tododefine.property2
     *
     * @return the value of t_tododefine.property2
     *
     * @mbggenerated
     */
    public String getProperty2() {
        return property2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tododefine.property2
     *
     * @param property2 the value for t_tododefine.property2
     *
     * @mbggenerated
     */
    public void setProperty2(String property2) {
        this.property2 = property2 == null ? null : property2.trim();
    }
}