package com.utonw.dealer.mapper;


import java.util.List;

import com.utonw.dealer.api.entity.CsdApprovalInfo;

public interface CsdApprovalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int insert(CsdApprovalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int insertSelective(CsdApprovalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    CsdApprovalInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CsdApprovalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CsdApprovalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsdApprovalInfo record);

    List<CsdApprovalInfo> selectAllByOrderUUID(String id);
}