package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.CsdApprovalInfo;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
@Component
public interface CsdApprovalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int insert(CsdApprovalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int insertSelective(CsdApprovalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    CsdApprovalInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CsdApprovalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CsdApprovalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csd_approval_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsdApprovalInfo record);

    List<CsdApprovalInfo> selectAllByOrderUUID(List<String> id);
    List<CsdApprovalInfo> selectAllByOrderId(String id);
	Map selectByApplyId(String string);
	String selectNameByOrderIdOrderByApprovalTime(String orderId);
}