package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.erp.CustomerRegisterInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface CustomerRegisterInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_register_info
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_register_info
     */
    int insert(CustomerRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_register_info
     */
    int insertSelective(CustomerRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_register_info
     */
    CustomerRegisterInfo selectByPrimaryKey(String uuid);
    CustomerRegisterInfo selectByPrimaryKey1(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_register_info
     */
    int updateByPrimaryKeySelective(CustomerRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_register_info
     */
    int updateByPrimaryKeyWithBLOBs(CustomerRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_register_info
     */
    int updateByPrimaryKey(CustomerRegisterInfo record);

    /**
     * 字段唯一性验证
     *
     * @param paramMap 参数map
     * @return CustomerRegisterInfo
     */
    CustomerRegisterInfo verifyUniquenessFields(Map<String, Object> paramMap);

    /**
     * 根据条件查询客户信息
     *
     * @param param
     * @return <code>List<CustomerRegisterInfo></code>
     */
    List<CustomerRegisterInfo> selectCustomerWapper(Map param);

    Long queryYestdAddCus();
    
    CustomerRegisterInfo selectByIdCard(String idCard);

}