package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.erp.LoanReviewInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface LoanReviewInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_review_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_review_info
     *
     * @mbggenerated
     */
    int insert(LoanReviewInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_review_info
     *
     * @mbggenerated
     */
    int insertSelective(LoanReviewInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_review_info
     *
     * @mbggenerated
     */
    LoanReviewInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_review_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LoanReviewInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_review_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(LoanReviewInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_review_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LoanReviewInfo record);

    /**
     * 根据查询条件获取评审信息
     *
     * @param map 参数map
     * @return LoanReviewInfo
     */
    List<LoanReviewInfo> selectLoanReviewInfoCondition(Map<String, Object> map);
    List<LoanReviewInfo> selectLoancollectionrecords(Map<String, Object> map);
    //查询贷后所有的评审记录
    List<LoanReviewInfo> selectLoanAfterReviewrecords(Map<String, Object> map);

    List<LoanReviewInfo> selectByBusinessKeyAndUserId(@Param("loanId") String loanId, @Param("reviewLevel") String reviewLevel, @Param("reviewedById") String reviewedById);
    
    LoanReviewInfo selectByLoanIdAndReviewLevel(String loanId, String ReviewLevel);

    LoanReviewInfo queryLoanReviewInfoByLoanId(String loanId);

}