package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.MerchantIndent;

public interface MerchantIndentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_indent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_indent
     *
     * @mbggenerated
     */
    int insert(MerchantIndent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_indent
     *
     * @mbggenerated
     */
    int insertSelective(MerchantIndent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_indent
     *
     * @mbggenerated
     */
    MerchantIndent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_indent
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantIndent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_indent
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantIndent record);

    MerchantIndent selectIndentByOrderId(String orderId);
}