package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.erp.ModuleRole;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface ModuleRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_role
     *
     */
    int deleteByPrimaryKey(Integer rbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_role
     *
     */
    int insert(ModuleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_role
     *
     */
    int insertSelective(ModuleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_role
     *
     */
    ModuleRole selectByPrimaryKey(Integer rbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_role
     *
     */
    int updateByPrimaryKeySelective(ModuleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_role
     *
     */
    int updateByPrimaryKey(ModuleRole record);

    /**
     * 根据模块ID和角色ID获取列表
     *
     * @param moduleId
     * @param roleId
     * @return
     */
    List<ModuleRole> findListByModuleAndRole(@Param("moduleId") Integer moduleId, @Param("roleId") Integer roleId);


    /**
     * 删除未选中的模块
     *
     */
    int deleteNotInModule(Map<String, Object> map);

    /**
     * 根据角色Id查询模块列表
     * @param roleId
     * @return
     */
    List<ModuleRole> findModuleByRoleId(@Param("roleId") Integer roleId);

    /**
     * 根据模块ID查询出所有角色
     *
     * @param moduleId 模块ID
     */
    List<ModuleRole> findRoleByModuleId(@Param("moduleId") Integer moduleId);

    /**
     * 删除模块下的授权数据
     *
     * @param moduleId 模块ID
     * @return 0/1
     */
    int deleteInModuleId(@Param("moduleId") Integer moduleId);
}