package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.erp.ModuleManage;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface ModuleManageMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_manage
     *
     */
    int deleteByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_manage
     *
     */
    int insert(ModuleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_manage
     *
     */
    int insertSelective(ModuleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_manage
     *
     */
    ModuleManage selectByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_manage
     *
     */
    int updateByPrimaryKeySelective(ModuleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_manage
     *
     */
    int updateByPrimaryKey(ModuleManage record);

    /**
     * 查询出角色对应的模块
     *
     * @param map map参数
     * @return 模块list
     */
    List<ModuleManage> findMyModule(Map<String, Object> map);

    /**
     * 获取模块列表
     *
     * @return 模块列表
     */
    List<ModuleManage> getList();


    /**
     * 根据ID查找该ID下的子级模块
     *
     * @return ModuleManage list
     */
    List<ModuleManage> findModuleByPid(ModuleManage moduleManage);
}