package com.utonw.utonerp.mapper;

import com.github.pagehelper.Page;
import com.utonw.dealer.api.dto.request.OrderPageRequest;
import com.utonw.dealer.api.entity.RepaymentPlan;
import org.springframework.stereotype.Component;


import java.util.List;
import java.util.Map;

@Component
public interface RepaymentPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan
     *
     * @mbggenerated
     */
    int insert(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan
     *
     * @mbggenerated
     */
    int insertSelective(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan
     *
     * @mbggenerated
     */
    RepaymentPlan selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RepaymentPlan record);


    RepaymentPlan selectrepaymentPlan(String orderId);
    List<RepaymentPlan> selectByOrderIds(List<String> ids);

    Page<Map<String,Object>> selectAllByTaskList(OrderPageRequest request);

    RepaymentPlan  selectByOrderId(String orderId);

	void updateByOrderId(RepaymentPlan repaymentPlan);
}