package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.erp.RoleManage;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface RoleManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_manage
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_manage
     */
    int insert(RoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_manage
     */
    int insertSelective(RoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_manage
     */
    RoleManage selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_manage
     */
    int updateByPrimaryKeySelective(RoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_manage
     */
    int updateByPrimaryKey(RoleManage record);


    /**
     * 查询角色列表
     *
     * @param roleName
     * @return
     */
    List<RoleManage> getListByParam(@Param("roleName") String roleName);

    /**
     * 查询用户UUID未分配的个人角色
     *
     * @param uuid 用户UUID
     * @return <code>List<RoleManage></code>
     */
    List<RoleManage> findRoleManageNotInRoleUser(@Param("customerId") String customerId, @Param("userId") String userId);
    
    /**
     * 查询用户UUID未分配的分配角色
     *
     * @param uuid 用户UUID
     * @return <code>List<RoleManage></code>
     */
    List<RoleManage> findRoleManageNotInRoleAssign(@Param("customerId") String customerId, @Param("userId") String userId);

}