package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.erp.SysParamter;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SysParamterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     *
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     *
     */
    int insert(SysParamter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     *
     */
    int insertSelective(SysParamter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     *
     */
    SysParamter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     *
     */
    int updateByPrimaryKeySelective(SysParamter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     *
     */
    int updateByPrimaryKeyWithBLOBs(SysParamter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     *
     */
    int updateByPrimaryKey(SysParamter record);

    /**
     * @param companyId
     * @return SystemParamter
     */
    List<SysParamter> selectSysParameterById(Integer companyId);
}