package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.erp.SystemParameter;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface SystemParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     */
    int insert(SystemParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     */
    int insertSelective(SystemParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     */
    SystemParameter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     */
    int updateByPrimaryKeySelective(SystemParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     */
    int updateByPrimaryKeyWithBLOBs(SystemParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     */
    int updateByPrimaryKey(SystemParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_paramter
     */
    int updateBySysKey(SystemParameter record);

    /**
     * 查询所有的
     */
    List<SystemParameter> selectAllParameter();

    SystemParameter selectParameterByKey(@Param("companyId") Integer companyId, @Param("sysKey")
            String sys_key);

    List<SystemParameter> selectAllParameterByCompanyIdAndType(Map map);
}