package com.utonw.utonerp.mapper;


import com.utonw.dealer.api.entity.TDistributionRfid;
import com.utonw.dealer.api.vo.TDistributionRfidVo;
import com.utonw.dealer.api.entity.erp.MerchantApplyInfoEntity;
import java.util.List;
public interface TDistributionRfidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_distribution_rfid
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_distribution_rfid
     *
     * @mbggenerated
     */
    int insert(TDistributionRfid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_distribution_rfid
     *
     * @mbggenerated
     */
    int insertSelective(TDistributionRfid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_distribution_rfid
     *
     * @mbggenerated
     */
    TDistributionRfid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_distribution_rfid
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TDistributionRfid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_distribution_rfid
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TDistributionRfid record);

    List<TDistributionRfid> selecttDistributionRfidList(String uuid);
    
    void insertByDealerId(MerchantApplyInfoEntity merchantApplyInfoEntity);

    List<TDistributionRfidVo> showStatusIsOKAll();

}