package com.utonw.utonerp.mapper;


import com.utonw.dealer.api.entity.erp.TodoInsEntity;

public interface TodoInsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todoins
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todoins
     *
     * @mbggenerated
     */
    int insert(TodoInsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todoins
     *
     * @mbggenerated
     */
    int insertSelective(TodoInsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todoins
     *
     * @mbggenerated
     */
    TodoInsEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todoins
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TodoInsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todoins
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TodoInsEntity record);

    /**
     * 通过businessKey查询
     * @param businesskey
     * @return
     */
    TodoInsEntity findBybusinesskey(String businesskey);
}