package com.utonw.utonerp.mapper;

import com.utonw.dealer.api.entity.erp.UserLocate;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface UserLocateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_locate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_locate
     *
     * @mbggenerated
     */
    int insert(UserLocate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_locate
     *
     * @mbggenerated
     */
    int insertSelective(UserLocate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_locate
     *
     * @mbggenerated
     */
    UserLocate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_locate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserLocate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_locate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserLocate record);

    Integer deleteByUserId(String userId);
}