server:
      port: 8080
logging: 
  config: classpath:logback.xml 
spring:
  dubbo:
    application:
      name : provider
    registry:
      address: zookeeper://zk:2181?backup=uton.dealer.zookeeper2.com:2181,uton.dealer.zookeeper3.com:2181
    protocol:
      name: dubbo
      port: 20880
      serialization: hessian2
    scan: com.utonw
    consumer:
      timeout: 50000
    provider:
      timeout: 50000
  redis:
    host: redis
    port: 6379
    password: 
  datasource:
    continueOnError: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://db:3306/utonpms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      max-open-prepared-statements: 20
mybatis:
  type-aliases-package: com.utonw.dealer.api.entity
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
   map-underscore-to-camel-case: true
   use-generated-keys: true
   default-fetch-size: 100
   default-statement-timeout: 30
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql
    rowBoundsWithCount: true
    offsetAsPageNumz: true

appName: 买家端
appKey: buyer
message:
  userName: xczy
  password: thefirst
  expireTime: 60
image:
  path: D:\imge\
loanstage:
  review: datareview,judgment,lended
  repayment: repayment
  finish: end
pic:
  host: http://pic.utonw.com/
temporary:
  dir: /home/temporarydir
profile: prod_envrimont
AndriodAppKey: 58db5668c62dca62f4000253
AndriodAppMasterSecret: jihpramjdh3qd1x6i2qm5at1ojxqaows
AppKey: 585d07cf8f4a9d14c6001223
AppMasterSecret: ql8x4zimzo3k3y7aekvo4wilu0dr76rm
pengyuan:
  personal: http://112.74.101.138:3333/risk/personal?
  enterprise: http://112.74.101.138:3333/risk/enterprise?
  fraud: http://112.74.101.138:3333/risk/fraudInfo?
baidu:
  map:
    geoconv:
      url: http://api.map.baidu.com/geoconv/v1/
      ak: jniXRWzaM0kDoSHVG2DGL10rKUVKc2oL